name: arcade
channels:
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.9
  - pip:
    - arcade==2.5.5
    - attrs==21.2.0
    - cffi==1.14.5
    - numpy==1.20.1
    - pillow==8.2.0
    - pycparser==2.20
    - pyglet==1.5.17
    - pymunk==6.0.0
    - pyopengl-accelerate==3.1.5
    - pytiled-parser==0.9.4a3
    - pyyaml==5.4.1
    - shapely==1.7.1
